name: Deploy SAM App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Verify SAM
        run: sam --version

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::583543841419:role/GitHubActions
          aws-region: us-east-1

      - name: Build SAM app
        run: sam build

      - name: Deploy SAM app
        run: |
          sam deploy \
            --stack-name serverless-notes-api \
            --region us-east-1 \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset